/* Imports */
import React, { useState } from "react";
import BasicReport from './ChatGPTBasic';
import Questions from './BasicQuestions';
import TimerParts from './TimerParts';

function BasicPage() {
    // answers useState generated by GPT-4
    const [completedBasicQuestions, setCompletedBasicQuestions] = useState(false);
    const [answers] = useState({
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        answer5: "",
        answer6: "",
        answer7: ""
    });
    
    //ChatGPT-4 debugged updateCompletedBasicQuestions and handleAnswerChange as I used answers[A] instead of answers.answerA
    function updateCompletedBasicQuestions () {
        if(answers.answer1 !== "" && answers.answer2 !== "" && answers.answer3 !== "" && answers.answer4 !== "" && answers.answer5 !== "" 
        && answers.answer6 !== "" && answers.answer7 !== "") {
        }
    }

    function handleAnswerChange (answer: string, value: string) {
        if(answer === "answer1") {
            answers.answer1 = value;
        } else if (answer === "answer2") {
            answers.answer2 = value;
        } else if (answer === "answer3") {
            answers.answer3 = value;
        } else if (answer === "answer4") {
            answers.answer4 = value;
        } else if (answer === "answer5") {
            answers.answer5 = value;
        } else if (answer === "answer6") {
            answers.answer6 = value;
        } else if (answer === "answer7") {
            answers.answer7 = value;
        }
        updateCompletedBasicQuestions();
    };
    
    // GPT-4 used in the creation of parameters for Questions and BasicReport
    return (
        <div>
            {!completedBasicQuestions && <TimerParts />}
            {!completedBasicQuestions ? (
                <div>
                    <Questions onChange={handleAnswerChange} onSubmit={() => setCompletedBasicQuestions(true)} />
                </div>
            ) : (
                <div>
                    <BasicReport answers={answers} />
                </div>
            )}
            <div className={`box ${completedBasicQuestions ? 'show' : ''}`}>
            </div>
        </div>
    )
}
export default BasicPage